# v25_datacleaner configuration

[DAT] # housekeeping data
min_n_lines = 2 # minimum number of lines in a file of that type
n_cols = 13

[HAL] # IWG1 data from A/C
min_n_lines = 2
n_cols = 15

[MAS] # Caribic master data
min_n_lines = 2
n_cols = 4

[OMC] # Omcal UV photometer
min_n_lines = 2
n_cols = 18

[OSC] # Oscar CL detector
min_n_lines = 6
n_cols = 4

[T_P] # housekeeping data, temperatures and pressures
min_n_lines = 2
n_cols = 20
