# v25_datacleaner configuration
#
# this config file is expected to be in a directory 'cfg' next the the executable
#
#
[DAT] # housekeeping data
min_n_lines = 2 # minimum number of lines in a file of that type

[HAL] # IWG1 data from A/C
min_n_lines = 2

[MAS] # Caribic master data
min_n_lines = 2

[OMC] # Omcal UV photometer
min_n_lines = 2

[OSC] # Oscar CL detector
min_n_lines = 6

[T_P] # housekeeping data, temperatures and pressures
min_n_lines = 2
