name: build

on:
  push:
    tags:        
      - v*


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: build
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
