name: pyfuppes-tests

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"] # ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest] # , macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock" # invalidate cache if lockfile changes

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run black formatting
        run: uv run black . --color --diff --check

      - name: Run ruff ckecks
        run: uv run ruff check

      - name: Run tests
        run: uv run -m pytest
